name: enkanakku_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1 #Firebase core dependency
  firebase_auth: ^6.5.6 #Firebase core dependency
  # google_sign_in: ^7.2.0 #Firebase core dependency
  cloud_firestore: ^6.7.1 #Firebase core dependency
  firebase_crashlytics: ^5.2.6

  provider: ^6.1.5+1
  shared_preferences: ^2.0.15
  dio: ^5.11.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  android_package_installer: ^0.0.3
  permission_handler: ^12.0.3
  intl: ^0.20.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: "launcher_icon"
  # ios: true
  image_path: "lib/utils/images/app_logo.png"
  min_sdk_android: 21

  adaptive_icon_background: "#EEF6FF"
  adaptive_icon_foreground: "lib/utils/images/app_logo.png"


flutter:
  uses-material-design: true

  assets:
    - lib/utils/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
