// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdyujQ05ohZaSOFkZFip7uEj37KGa6vA',
    appId: '1:947449486608:web:cc065b505e29c7ed211995',
    messagingSenderId: '947449486608',
    projectId: 'enkanakku-app-dev',
    authDomain: 'enkanakku-app-dev.firebaseapp.com',
    storageBucket: 'enkanakku-app-dev.firebasestorage.app',
    measurementId: 'G-1TFRD3P75W',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCue5mqBFgeK8eVqU8b--XOmy5ykDP0PGA',
    appId: '1:947449486608:android:f4f40f8234e49c1c211995',
    messagingSenderId: '947449486608',
    projectId: 'enkanakku-app-dev',
    storageBucket: 'enkanakku-app-dev.firebasestorage.app',
  );
}
