// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKy-xKNarXBjXFyfzpi3y6VQS7b2U9gY4',
    appId: '1:753010084681:web:057e713deac04b23ff2898',
    messagingSenderId: '753010084681',
    projectId: 'enkanakku-app',
    authDomain: 'enkanakku-app.firebaseapp.com',
    storageBucket: 'enkanakku-app.firebasestorage.app',
    measurementId: 'G-YVH0RFCWHP',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANbKWj3AJ2Sxbk3AYjhg8fQoID5q-huw0',
    appId: '1:753010084681:android:e83cc1eebf6ec9eeff2898',
    messagingSenderId: '753010084681',
    projectId: 'enkanakku-app',
    storageBucket: 'enkanakku-app.firebasestorage.app',
  );
}
